services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

  notification.workers:
    image: ${DOCKER_REGISTRY-}notificationworkers
    build:
      context: .
      dockerfile: Workers/Notification/Notification.Workers/Dockerfile


  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Services/Notification/Notification.API/Dockerfile


  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpAPIGateway/Dockerfile

